/**
 * esbuild Configuration for PKM Note Recommender Plugin
 *
 * Usage:
 *   npm run dev   - Development build with watch mode
 *   npm run build - Production build
 */

import esbuild from 'esbuild';
import process from 'node:process';
import builtins from 'builtin-modules';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
PKM Note Recommender - https://github.com/eohjun/obsidian-pkm-note-recommender
*/
`;

const prod = process.argv[2] === 'production';
const outdir = 'dist';

// Ensure output directory exists
if (!fs.existsSync(outdir)) {
  fs.mkdirSync(outdir, { recursive: true });
}

// Copy static files
fs.copyFileSync('manifest.json', path.join(outdir, 'manifest.json'));
if (fs.existsSync('styles.css')) {
  fs.copyFileSync('styles.css', path.join(outdir, 'styles.css'));
}
if (fs.existsSync('versions.json')) {
  fs.copyFileSync('versions.json', path.join(outdir, 'versions.json'));
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(outdir, 'main.js'),
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log('Watching for changes...');
}
